version: "3.7"

services:
  database_expenses:
    image: postgres
    container_name: database_expenses
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=expenses
      - POSTGRES_DB=expenses
    volumes:
      - pgdata:/data/postgres
  app:
    restart: always
    build: .
    container_name: dockercontainermyexpanses
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_expenses
    depends_on:
      - database_expenses
volumes:
  pgdata:
    driver: local
